spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:50000}/${POSTGRES_DB:admin_bd}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Initialize SQL scripts (data.sql) after JPA creates schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

security.jwt.secret=${JWT_SECRET:security.jwt.secret=K8vR2Yw7mZpFJxS4QnC9dE6A5uH0bB+oTtM3Lr1iWsGZk=}
security.jwt.access-ttl-seconds=${JWT_ACCESS_TTL_SECONDS:900}
security.jwt.refresh-ttl-seconds=${JWT_REFRESH_TTL_SECONDS:604800}

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=certs/rbpo_keystore_1BIB23403.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=admin123
server.ssl.key-alias=rbpo-1BIB23403



